### ISSUE TITLE
Question: Extension still valid with new Azure DevOps feature?

### ISSUE THREAD

**Issue by SebastianSchuetze** [cschleiden/vsts-markdown#17]
Hi Christopher,

just a question. Will your extension still be valid one the following features has been implemented?

[Work Item support for Markdown editing](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1221138)

Good work by the way. Is this feature implementation your work?

**Comment by cschleiden** [comment]
That feature would make the extension obsolete, yes. However, while we still hope to get to it, it won't be done in the immediate future.
