### ISSUE TITLE
Install tfs 2015 update 3

### ISSUE THREAD

**Issue by verysimplenick** [cschleiden/vsts-markdown#2]
Hi, I'm newbie on tfs, need some help.
I prefer use markdown for text layout and want add markdown support to our task description.
How I can do this? Or it's only for cloud version?

**Comment by cschleiden** [comment]
Since it's still in preview, I have only enabled install on the cloud version, so far. Once it becomes more stable I do want to provide an on-premise version as well, but it will take some more time.
